[project]
name = "replay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.1",
    "spotify2tidal>=1.1",
    "streamlit>=1.51.0",
    "tqdm>=4.67.1",
]
